<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <ProjectReference Include="..\LakeSpeak.Genie\LakeSpeak.Genie.csproj" />
    <ProjectReference Include="..\LakeSpeak.Configuration\LakeSpeak.Configuration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LakeSpeak.Application.Tests" />
  </ItemGroup>

</Project>
