<Project Sdk="Microsoft.NET.Sdk">

<ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <ProjectReference Include="..\..\src\LakeSpeak.Application\LakeSpeak.Application.csproj" />
    <ProjectReference Include="..\..\src\LakeSpeak.Configuration\LakeSpeak.Configuration.csproj" />
  </ItemGroup>

</Project>
