<Project Sdk="Microsoft.NET.Sdk">

<ItemGroup>
    <PackageReference Include="NSubstitute" />
    <ProjectReference Include="..\..\src\LakeSpeak.QuestionPacks\LakeSpeak.QuestionPacks.csproj" />
    <ProjectReference Include="..\..\src\LakeSpeak.Configuration\LakeSpeak.Configuration.csproj" />
  </ItemGroup>

</Project>
