<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NSubstitute" />
    <ProjectReference Include="..\..\src\LakeSpeak.QuestionPacks\LakeSpeak.QuestionPacks.csproj" />
  </ItemGroup>

</Project>
