<Project Sdk="Microsoft.NET.Sdk">

<ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="WireMock.Net" />
    <ProjectReference Include="..\..\src\LakeSpeak.Genie\LakeSpeak.Genie.csproj" />
  </ItemGroup>

</Project>
